# Generated by Django 5.1.2 on 2024-11-15 09:02

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-updated',)},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.CharField(default='Default body content', max_length=6000, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
